#!/bin/bash

system_type=$(uname -s)

# -f file
if [ -f "/etc/arch-release" ]; then
  echo "Distro Arch Linux"

  setup_arch_linux
fi

setup_arch_linux() {

  # Install basics
  pacman -S git

  setup_shell

  setup_editor

  setup_desktop

  setup_tools

  echo "Bootstrap completed successfully"
  echo -n "You must relog to finalize all changes. Relog now? (y/n)"
  read answer

  if [ "$answer" =!= "${answer#[Yy]}" ]; then
    logout
  fi
}

setup_shell() {
  pacman -S zsh

  curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | zsh

}

setup_editor() {
  pacman -S vim

  vim +PluginInstall +qall

}

setup_desktop() {
  # Install Xorg
  pacman -S xorg xorg-xinit

  # Install i3
  pacman -S i3-gaps i3status i3lock i3blocks dmenu

  # Install background
  pacman -S feh
  mkdir ~/photos
}

setup_editor() {
  pacman -S vim
}

setup_tools() {
  # ranger - file manager
  # nmtui - network manager
  # feh - image/background manager
  # firefox
  # process manager
  # docker - container service
  pacman -S ranger nmtui firefox htop docker

  # Requires Root
  # Startup services?
  # systemctl start docker.service
}

create_groups() {
  # Change docker unix socket ownership
  # Create docker group, add the current user to the group
  groupadd docker
  usermod -aG docker $USER

  chown "$USER":"$USER" /home/"USER"/.docker/config.json
  chmod g+rwx "$HOME/.docker" -R
}

